---
- name: install service
  become: yes
  become_user: root
  register: matchbox_config_service_change
  with_items:
    - f: matchbox.service
      d: /etc/systemd/system
  template:
    src: '{{ item.f }}.j2'
    dest: '{{ item.d }}/{{ item.f }}'
    mode: 0644

- name: systemctl daemon-reload
  become: yes
  become_user: root
  when: matchbox_config_activate and matchbox_config_service_change is changed
  systemd:
    daemon_reload: yes

- name: launching matchbox...
  when: matchbox_config_activate
  become: yes
  become_user: root
  service:
    name: matchbox
    enabled: yes
    state: started
