---
- name: install service
  become: yes
  become_user: root
  notify: matchbox_config_service_changed
  template:
    src: matchbox.service.j2
    dest: '{{ matchbox_config_systemd_unit_path }}/{{ matchbox_config_systemd_unit }}'
    mode: 0644

- name: launching matchbox...
  when: matchbox_config_activate | bool
  become: yes
  become_user: root
  service:
    name: '{{ matchbox_config_service_name }}'
    enabled: yes
    state: started
