---
# handlers file for matchbox-config
- name: matchbox_config_service_changed
  become: yes
  become_user: root
  when: matchbox_config_activate | bool
  systemd:
    name: '{{ matchbox_config_service_name }}'
    daemon_reload: yes
    state: restarted
